name: DVE Test
on: [push, pull_request]
jobs: 
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Deploy DVE
      run: |
        cd docker/
        docker-compose up -d
        
    - name: Push Images
      run: |
        docker push shawnsky/hshe-core:v1.0
        docker push shawnsky/hshe-judge:v1.0
        docker push shawnsky/hshe-sim:v1.0

        
